### ISSUE TITLE
Implement mechanism to indicate that artifacts (including POM) should be GPG signed

### ISSUE THREAD

**Issue by harningt** [ajoberstar/gradle-defaults#1]
Trying to setup my build to use gradle-defaults to re-use the new maven-publish architecture is leading to problems due to the fact that using it as-is does not give me a chance to get at the generated POM file and sign it.

It would be a great enhancement to this toolset to implement artifact signing in a generic fashion (perhaps a 'signing' true option in defaults).

See the following for how someone managed to wrangle maven-publish to do code-signing.
https://mike-neck.github.io/blog/2013/06/21/how-to-publish-artifacts-with-gradle-maven-publish-plugin-version-1-dot-6/

In the mean-time, I'm stuck with old-style maven publishing and re-implementing the POM generation process.

**Comment by ajoberstar** [comment]
From what I remember the new `*-publish` plugins don't support signing at all right now. The signing supported in `gradle-defaults` is through the Bintray plugin. I think adding support for signing through the `*-publish` plugins is something that should be added to core Gradle rather than this plugin.
